# Generated by Django 2.2.5 on 2019-10-22 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_auto_20191018_1600'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='name',
            new_name='title',
        ),
    ]
