# Generated by Django 2.2.5 on 2019-10-22 14:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_auto_20191022_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='files',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
